export const DEFAULT_EXCLUDES = [
  '**/.git/**',
  '**/.svn/**',
  '**/.hg/**',

  '**/node_modules/**',
  '**/vendor/**',
  '**/.venv/**',
  '**/venv/**',
  '**/.pnpm-store/**',

  '**/dist/**',
  '**/build/**',
  '**/out/**',
  '**/.next/**',
  '**/.nuxt/**',
  '**/.turbo/**',
  '**/.parcel-cache/**',
  '**/.cache/**',
  '**/coverage/**',
  '**/target/**',
  '**/bin/**',
  '**/obj/**',
  '**/public/build/**',

  '**/__pycache__/**',
  '**/.mypy_cache/**',
  '**/.pytest_cache/**',
  '**/.tox/**',
  '**/.nox/**',
  '**/.ruff_cache/**',
  '**/.ccls-cache/**',

  '**/logs/**',
  '**/log/**',
  '**/bootstrap/cache/**',
  '**/storage/**',

  '**/.env',
  '**/.env.*',

  '**/.idea/**',
  '**/.vscode/**',
  '**/*.iml',

  '**/*.lock',
  '**/*.min.*',
  '**/*.log',
  '**/*.tmp',
  '**/*.temp',
  '**/*.bak',

  '**/*.exe',
  '**/*.dll',
  '**/*.so',
  '**/*.dylib',
  '**/*.lib',
  '**/*.a',
  '**/*.o',
  '**/*.class',
  '**/*.jar',
  '**/*.war',
  '**/*.ear',

  '**/*.iso',
  '**/*.zip',
  '**/*.gz',
  '**/*.tgz',
  '**/*.bz2',
  '**/*.xz',
  '**/*.7z',

  '**/.DS_Store',
  '**/Thumbs.db',
  '**/desktop.ini',

  '**/npm-debug.log*',
  '**/yarn-debug.log*',
  '**/yarn-error.log*',
  '**/pnpm-debug.log*',
  '**/lerna-debug.log*',
  '**/*.swp'
];
